### ISSUE TITLE
请问windows 10 64位下运行提示bpylist无法导入怎么处理

### ISSUE THREAD

**Issue by wynnforthework** [dkw72n/idb#9]
系统版本：windows 10 64位，cpu是inter
python版本：3.10

克隆到本地运行提示bpylist无法导入，于是我尝试pip install bpylist，安装编译失败，根据提示安装vs build，安装后提示：
`ERROR: Command errored out with exit status 1: 'd:\ProgramData\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-ytuw1qdl\\bpylist_3e6d65dbccd74ff796f45649803bc8ec\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-ytuw1qdl\\bpylist_3e6d65dbccd74ff796f45649803bc8ec\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Administrator\AppData\Local\Temp\pip-record-wygzt1qf\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\ProgramData\Anaconda3\Include\bpylist' Check the logs for full command output.`

请问这种情况怎么处理？

**Comment by wynnforthework** [comment]
我在macos下执行提示bplist无法导入，
python版本：3.9
`$ (master) python app.py devices
Traceback (most recent call last):
  File "/Users/wynn/Documents/gitclone/idb/app.py", line 9, in <module>
    from afc_service import AfcService
  File "/Users/wynn/Documents/gitclone/idb/afc_service.py", line 8, in <module>
    from libimobiledevice import AfcError, AfcFileMode, AfcLinkType
  File "/Users/wynn/Documents/gitclone/idb/libimobiledevice/__init__.py", line 3, in <module>
    from bpylist import archiver, bplist
  File "/Users/wynn/Documents/gitclone/idb/bpylist/archiver.py", line 1, in <module>
    from bpylist import bplist
ImportError: cannot import name 'bplist' from 'bpylist' (/Users/wynn/Documents/gitclone/idb/bpylist/__init__.py)`

**Comment by wynnforthework** [comment]
`发生异常: OSError
dlopen(/Users/*****/Documents/gitclone/idb/libimobiledevice/macos/libcrypto.1.1.dylib, 6): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/*****/Documents/gitclone/idb/libimobiledevice/macos/libcrypto.1.1.dylib (which was built for Mac OS X 10.15)`

**Comment by dkw72n** [comment]
仓库里的 bpylist 只支持 python3.7(windows/macOS) 和 python3.6(linux)
